# Generated by Django 4.2.4 on 2023-09-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renda',
            options={'ordering': ['owner', 'tipo'], 'verbose_name': 'Renda', 'verbose_name_plural': 'Rendas'},
        ),
    ]
