# Generated by Django 4.2.4 on 2023-10-01 13:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('renda', '0003_alter_renda_options_alter_tiporenda_nome'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tiporenda',
            unique_together={('owner', 'nome')},
        ),
    ]
