# Generated by Django 4.2.4 on 2023-12-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renda', '0004_alter_tiporenda_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='renda',
            options={'ordering': ['owner', '-data'], 'verbose_name': 'Renda', 'verbose_name_plural': 'Rendas'},
        ),
    ]
