# Generated by Django 4.2.4 on 2023-09-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasto', '0002_alter_tipogasto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(default='Cartão', max_length=50, verbose_name='Nome'),
        ),
    ]
