# Generated by Django 4.2.4 on 2023-09-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasto', '0003_alter_categoria_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='descricao',
            field=models.CharField(max_length=50, null=True, verbose_name='Descrição'),
        ),
    ]
