# Generated by Django 4.2.4 on 2023-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasto', '0004_gasto_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['-data', 'tipo', 'categoria'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(default='Uber', max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tipogasto',
            name='nome',
            field=models.CharField(default='Cartão de Crédito', max_length=50, verbose_name='Nome'),
        ),
    ]
