# Generated by Django 4.2.4 on 2023-09-23 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasto', '0005_alter_gasto_options_alter_categoria_nome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['owner', 'nome_categoria'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='tipogasto',
            options={'ordering': ['owner', 'nome_tipo'], 'verbose_name': 'Tipo de Gastos', 'verbose_name_plural': 'Tipos de Gastos'},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='nome_categoria',
        ),
        migrations.RenameField(
            model_name='tipogasto',
            old_name='nome',
            new_name='nome_tipo',
        ),
    ]
