# Generated by Django 4.2.4 on 2023-09-07 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInvestimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Ações', max_length=50, unique=True, verbose_name='Nome')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Tipo de Investimento',
                'verbose_name_plural': 'Tipos de Investimento',
                'ordering': ['owner', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11, null=True, verbose_name='Valor')),
                ('data', models.DateField(verbose_name='Data')),
                ('operacao', models.CharField(choices=[('Compra', 'Compra'), ('Venda', 'Venda')], default='Compra', max_length=50, verbose_name='Tipo de Operação')),
                ('obs', models.CharField(blank=True, default='Sem Obervações', max_length=255, verbose_name='Observações')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investimento.tipoinvestimento')),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
                'ordering': ['owner', 'tipo'],
            },
        ),
    ]
