# Generated by Django 4.2.4 on 2023-09-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investimento', '0002_investimento_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoinvestimento',
            name='nome',
            field=models.CharField(default='Ações', max_length=50, verbose_name='Nome'),
        ),
    ]
